# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WF-EpiDncSsu0G5txg5o1McrLuTmz8YI
"""

#Day 1
Li=[1, 3,5,7,9]
Li.reverse()
print(Li)

