# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F2JCLYt0hqrvjVvJKw4LdOT7RoWx988J
"""

# Final Project - Celsius to Fahrenheit converter
def temp(cel) :
  fahr=(cel*9/5) + 32
  return fahr
cel = int(input (" Enter temperature in Celsius")) 
temp(cel) 
print(temp(cel))